<?php

define('MBG', TRUE);
include($_SERVER['DOCUMENT_ROOT'] . '/flipcard/functions-new.php');

$META_TITLE = "Paraverse Flipcard Puzzle";
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paraverse Flipcard Puzzle</title>
    <link rel="stylesheet" href="assets/Paraverse logo/css/cardflip.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Galaxy background -->
    <div class="galaxy-bg">
        <div class="stars"></div>
        <div class="stars2"></div>
        <div class="stars3"></div>
    </div>

    <!-- Header -->
    <header class="header">
        <div class="logo">
            <img src="assets/Paraverse logo/ParaverseLogo.svg" alt="Logo" class="logo-icon-img" style="width: 24px; height: auto;">
            <div class="logo-text">
                <span class="logo-title">PARAVERSE</span>
                <span class="logo-subtitle">PUZZLE CARD GAME</span>
            </div>
        </div>
    </header>

    <main class="main-content">
        <h1 class="title">FLIP THE CARD</h1>
        <p class="subtitle">All cards start face-down · Choose your grid</p>
        <button class="grid-size-btn">5 × 5</button>

        <div class="grid-container" id="grid-container">
            <!-- Cards will be generated by JS -->
        </div>

        <div class="status-bar">
            <div class="status-item">
                <span class="status-label">GRID SIZE</span>
                <span class="status-value">5 × 5</span>
            </div>
            <div class="status-item">
                <span class="status-label">TOTAL CARDS</span>
                <span class="status-value">25</span>
            </div>
            <div class="status-item">
                <span class="status-label">STATUS</span>
                <span class="status-value" id="game-status">FACE DOWN</span>
            </div>
        </div>
    </main>

    <!-- Modals -->
    <!-- Trivia Modal -->
    <div class="modal-overlay" id="trivia-modal">
        <div class="modal blue-modal">
            <div class="modal-header">
                <button class="close-btn" onclick="closeModal('trivia-modal')">✕ CLOSE</button>
            </div>
            <div class="modal-content">
                <div class="emoji">⭐</div>
                <h2 class="modal-heading text-blue" id="trivia-heading">TRIVIA!</h2>
                <p id="trivia-text">Ano ang pambansang bulaklak ng Pilipinas?</p>
                <div class="trivia-options" id="trivia-options"></div>
            </div>
        </div>
    </div>

    <!-- Wrong Modal -->
    <div class="modal-overlay" id="wrong-modal">
        <div class="modal red-modal">
            <div class="modal-header">
                <button class="close-btn" onclick="closeModal('wrong-modal')">✕ CLOSE</button>
            </div>
            <div class="modal-content">
                <div class="emoji">😱</div>
                <h2 class="modal-heading text-red" id="wrong-heading">HALA!!</h2>
                <p id="wrong-text">Ay sus, bokya ka!</p>
            </div>
        </div>
    </div>

    <!-- Sliding Puzzle Overlay -->
    <div class="overlay" id="sliding-puzzle-overlay">
        <div class="sliding-puzzle-container">
            <div class="sliding-grid" id="sliding-grid">
                <!-- 3x3 tiles generated by JS -->
            </div>
            <div class="sliding-sidebar">
                <div class="sliding-header">
                    <img src="assets/Paraverse logo/ParaverseLogo.svg" alt="Logo" class="sliding-logo-icon-img" style="width: 32px; height: auto;">
                    <div class="sliding-header-text">
                        <h3>Sliding Puzzle</h3>
                        <p>RESTORE THE LOGO</p>
                    </div>
                </div>
                <div class="stats">
                    <div class="stat-box">
                        <span>MOVES</span>
                        <h2 id="moves-count">0</h2>
                    </div>
                    <div class="stat-box">
                        <span>TIME LEFT</span>
                        <h2 id="time-left">02:59</h2>
                    </div>
                </div>
                <div class="progress-bar"><div class="progress" id="time-progress"></div></div>
                <button class="btn btn-restart" id="btn-restart">↺ RESTART</button>
                <button class="btn btn-giveup" id="btn-giveup">⊘ GIVE UP</button>
                <button class="btn-mute" id="btn-mute">🔊 Mute</button>
            </div>
        </div>
    </div>
    
    <!-- Winner Modal -->
    <div class="modal-overlay" id="winner-modal">
        <div class="modal blue-modal">
            <div class="modal-header">
                <button class="close-btn" onclick="closeModal('winner-modal')">✕ CLOSE</button>
            </div>
            <div class="modal-content">
                <div class="emoji">🎉</div>
                <h2 class="modal-heading text-blue">WINNER!</h2>
                <p>Congratulations! You have restored the logo and paired all the cards!</p>
            </div>
        </div>
    </div>

    <!-- Game Over Modal -->
    <div class="modal-overlay" id="game-over-modal">
        <div class="modal red-modal">
            <div class="modal-header">
                <button class="close-btn" onclick="closeModal('game-over-modal')">✕ CLOSE</button>
            </div>
            <div class="modal-content">
                <div class="emoji">⏱️</div>
                <h2 class="modal-heading text-red">TIME'S UP!</h2>
                <p>Thank you for playing! You did your best to this point.</p>
                <button class="btn btn-restart" onclick="location.reload()" style="margin-top: 20px;">↻ WANT TO TRY AGAIN?</button>
            </div>
        </div>
    </div>

    <script src="assets/Paraverse logo/js/script.js"></script>
</body>
</html>
