<?php

define('MBG', TRUE);
include($_SERVER['DOCUMENT_ROOT'] . '/card-flip-puzzle/functions-new.php');

//IS_LOGGED_IN($_SERVER['REQUEST_URI']);

$META_TITLE = "Welcome to Edith";
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <?php HEAD_ESSENTIALS(); ?>
  <link rel="stylesheet" href="assets/vars_index.css">
  <link rel="stylesheet" href="assets/style_index.css">
  <link rel="stylesheet" href="assets/style_revealed.css">
  <link rel="stylesheet" href="assets/style_win-feu-tech.css">
  <link rel="stylesheet" href="assets/style_lose.css">
  <link rel="stylesheet" href="assets/style_completed.css">
  <link rel="stylesheet" href="assets/style_congratulation.css">
  <link rel="stylesheet" href="assets/game_interaction.css">
  <link href="/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
  <script src="/assets/plugins/custom/datatables/datatables.bundle.js" defer></script>
</head>

<body id="kt_app_body" data-kt-app-page-loading-enabled="true" data-kt-app-page-loading="on"
  data-kt-app-layout="light-header" class="app-default">
  <?php include("partials/_page-loader.php"); ?>
  <div class="d-flex flex-column flex-root app-root" id="kt_app_root">
    <div class="app-page flex-column flex-column-fluid" id="kt_app_page">
      <?php include("partials/_header.php"); ?>
      <div class="app-wrapper flex-column flex-row-fluid" id="kt_app_wrapper">
        <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
          <div class="d-flex flex-column flex-column-fluid">
            <main>
              <div class="app-container container-xxl">
<div class="card-back-view-5-x-5-puzzle-card-game-design">
    <div class="app">
      <div class="header">
        <div class="container">
          <div class="logo-mark">
            <img class="paraverse-logo" src="assets/paraverse-logo0.svg" />
          </div>
          <div class="container2">
            <div class="paragraph">
              <div class="paraverse">PARAVERSE</div>
            </div>
            <div class="paragraph2">
              <div class="puzzle-card-game">PUZZLE CARD GAME</div>
            </div>
          </div>
        </div>
      </div>
      <div class="container3">
        <div class="heading-1">
          <div class="flip-the-card">FLIP THE CARD</div>
        </div>
        <div class="paragraph3">
          <div class="all-cards-start-face-down-choose-your-grid">
            All cards start face‑down · Choose your grid
          </div>
        </div>
      </div>
      <div class="container4">
        <div class="button">
          <div class="_3-3">3 × 3</div>
        </div>
        <div class="button2">
          <div class="_4-4">4 × 4</div>
        </div>
        <div class="button3">
          <div class="_5-5">5 × 5</div>
        </div>
      </div>
      <div class="container-margin">
        <div class="container5">
          <div class="container6">
            <div class="text">
              <div class="grid-size">GRID SIZE</div>
            </div>
            <div class="text">
              <div class="_5-52" id="stat-grid-size">5 × 5</div>
            </div>
          </div>
          <div class="container6">
            <div class="text">
              <div class="total-cards">TOTAL CARDS</div>
            </div>
            <div class="text">
              <div class="_25" id="stat-total-cards">25</div>
            </div>
          </div>
          <div class="container6">
            <div class="text">
              <div class="status">STATUS</div>
            </div>
            <div class="text">
              <div class="face-down" id="stat-status">FACE DOWN</div>
            </div>
          </div>
        </div>
      </div>
      <div id="game-grid" class="_5-x-5-landscape">
        <!-- Dynamically generated by game.js -->
      </div>
      <div class="_25-cards-advanced">25 cards · ADVANCED</div>

      <!-- MODALS WRAPPERS -->
      
      <!-- Trivia / Question Modal -->
      <div class="win-5-x-5-puzzle-card-game-design" id="trivia-modal-wrapper" style="display: none;">
        <div class="card-modal">
          <div class="container17">
            <div class="container18">
              <div class="container19"></div>
              <div class="container20"></div>
              <div class="container21"></div>
              <div class="container22"></div>
              <div class="container23"></div>
              <div class="div2">⭐</div>
              <div class="container24"></div>
              <div class="trivia">Trivia!</div>
              <div class="ano-ang-pambansang-bulaklak-ng-pilipinas">
                Ano ang pambansang bulaklak ng Pilipinas?
              </div>
            </div>
            <div class="button4">
              <div class="close">✕ CLOSE</div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Lose / Bokya Modal -->
      <div class="win-5-x-5-puzzle-card-game-design" id="lose-modal-wrapper" style="display: none;">
        <div class="card-modal">
          <div class="container17">
            <div class="container18">
              <div class="container19"></div>
              <div class="container20"></div>
              <div class="container21"></div>
              <div class="container22"></div>
              <div class="container23"></div>
              <div class="container24"></div>
              <div class="frame-4">
                <div class="div2">😱</div>
                <div class="hala">HALA!!</div>
                <div class="ay-sus-bokya-ka">Ay sus, bokya ka!</div>
              </div>
            </div>
            <div class="button4">
              <div class="close">✕ CLOSE</div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Sliding Puzzle Modal -->
      <div class="win-5-x-5-puzzle-card-game-design" id="puzzle-modal-wrapper" style="display: none;">
        <div class="card-modal">
          <div class="create-sliding-puzzle">
            <div class="app2">
              <div class="placeholder-for-sliding-puzzle"></div>
            </div>
            <div class="galaxy-background-2" style="
                          background: url(assets/galaxy-background-20.png) center;
                          background-size: contain;
                          background-repeat: no-repeat;
                        ">
              <div class="container88">
                <div class="container89">
                  <div class="container90">
                    <!-- Tiles will be dynamically populated here -->
                  </div>
                </div>
                <div class="container-margin2">
                  <div class="container112"></div>
                </div>
                <div class="container113">
                  <div class="container114">
                    <div class="container115">
                      <div class="icon9">
                        <img class="clip-path-group" src="assets/clip-path-group0.svg"/>
                      </div>
                      <div class="container116">
                        <div class="container93">
                          <div class="sliding-puzzle">Sliding Puzzle</div>
                        </div>
                        <div class="container93">
                          <div class="restore-the-logo">Restore the logo</div>
                        </div>
                      </div>
                    </div>
                    <div class="container117"></div>
                    <div class="container118">
                      <div class="container119">
                        <div class="container93">
                          <div class="moves">Moves</div>
                        </div>
                        <div class="container-margin3">
                          <div class="_181">0</div>
                        </div>
                      </div>
                      <div class="container120">
                        <div class="container121">
                          <div class="time-left">Time Left</div>
                        </div>
                        <div class="container-margin4">
                          <div class="_02-58">02:58</div>
                        </div>
                      </div>
                    </div>
                    <div class="container122">
                      <div class="container123"></div>
                    </div>
                  </div>
                  <div class="container124" style="display: none;">
                    <div class="solved-in-181-moves">🎉 Solved in 0 moves!</div>
                  </div>
                  <div class="container125" style="display: none;">
                    <div class="button4">
                      <div class="div2">👀</div>
                      <div class="reveal-the-card">REVEAL THE CARD</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Congratulations Modal -->
      <div class="win-5-x-5-puzzle-card-game-design" id="congratulations-modal-wrapper" style="display: none;">
        <div class="card-modal">
          <div class="container88">
            <div class="container89">
              <div class="container90"></div>
              <div class="container91"></div>
              <div class="container92"></div>
              <div class="container93"></div>
              <div class="container94"></div>
              <div class="container95"></div>
            </div>
            <div class="frame-5">
              <div class="div2">🎊</div>
              <div class="container96">
                <div class="congratulations">CONGRATULATIONS</div>
              </div>
              <div class="you-win">YOU WIN!</div>
              <div class="button4">
                <div class="play-again">Play again</div>
              </div>
            </div>
            <div class="button5">
              <div class="close">✕ CLOSE</div>
            </div>
          </div>
        </div>
      </div>25 cards · ADVANCED</div>
    </div>
  </div>
              </div>
            </main>
          </div>
          <?php include("partials/_footer.php"); ?>
        </div>
      </div>
    </div>
  </div>
  <?php include("partials/_scrolltop.php"); ?>
  <script src="assets/game.js" defer></script>
</body>

</html>
